[package]
name = "nes_emulator"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "emulator_loop"
path = "src/emulator_loop.rs"

[dependencies]
lazy_static = "1.4.0"
macroquad = "0.4.14"

[dependencies.bitflags]
version = "2.9.1"
